### PR TITLE
ensure inheritanceDT is nonempty before doing comparison.  Fixes #256

### LINKED ISSUE #256: CreatePackageReport() breaks on bad logical condition
I'm unsure of the exact issue, but the following code

```r
pkg_name <- YOUR_PACKAGE_NAME
CreatePackageReport(
    pkg_name
    , report_path = file.path(getwd(), "report.html")
)
```

Yields an error like the following on the Function Network tab (generated by `FunctionReporter`):

```
## Error in if (is.na(out) && inheritanceDT[CLASS_NAME == parent_name, !is.na(PARENT_NAME) && : missing value where TRUE/FALSE needed
```

I've observed this error for the following packages:

* `callr`
* `pkgbuild`
* `rcmdcheck`

discovered via the code in #252

### PR DESCRIPTION
**Pull request by TylerGrantSmith**
Just added a simple row count check before comparing data table values.   Otherwise the result of the `data.table` command is `NA`

### CODE REVIEW

**Comment by TylerGrantSmith** [comment]
@jameslamb I got the same error that was originally listed in #256 
`## Error in if (is.na(out) && inheritanceDT[CLASS_NAME == parent_name, !is.na(PARENT_NAME) && : missing value where TRUE/FALSE needed`

I will see what I can do about the unit test.  I have never made a test for an R6 method, so I will try to base it off what you all have done in the other tests.

**Comment by jayqi** [comment]
I think the way to test this is to have some class A's method depend on an inherited class B's method, where class B is in a different package. 

I feel like this may end up being a somewhat involved test to write, so feel free to open an issue about it, to capture the need, and we can just merge this change as is so it's not blocked.

**Comment by TylerGrantSmith** [comment]
> I feel like this may end up being a somewhat involved test to write (we'd need two test packages? or make a new test package depend on an existing test package?)

I agree, and that is why I haven't worked on the test yet.  It does raise a methodological question for me though.  If you were to take the latter path and modify an existing test package, what checks are there to guarantee it doesn't "break" the tests it was originally designed for.  

For example, with with the `silverstein` test package in #263, the structure of the classes is fairly specific and it would be easy to modify the package in a way that would not cause the associated test to fail, but the test would not be working as intended.

**Comment by jayqi** [comment]
@TylerGrantSmith I've opened #265 to document this missing test. Let's move the discussion there.

**Pull request merged**
