### PR TITLE
removed redundant colons from docs

### LINKED ISSUE #277: [docs] Parameter doc section has unnecessary leading `:`
If you run `?pkgnet::InheritanceReport`, you'll see a section like this:

image

And the same on the `pkgdown` site (https://uptake.github.io/pkgnet/reference/InheritanceReporter.html)

image

Since the parameter names are nicely being put in their own left-aligned heading and then the description is indented over, I think we should remove the leading `: `. It looks out of place.

Not sure if this is affecting other documentation in the project, but whoever picks up this issue should look at all of it.

### PR DESCRIPTION
**Pull request by KKulma**
resolves #277

### CODE REVIEW

**Review by jameslamb — COMMENTED** [review]
Thanks for taking the time to contribute to `{pkgnet}`, @KKulma ! This looks good to me, but I'll double check tonight by re-installing the package and running `?CreatePackageReport`

I did notice one issue...did you notice that this commit doesn't mention your username?

image

I've had that situation before doing open source stuff. I think you should fix this before we merge, so you'll show up in the list of `{pkgnet}` contributors!

In case you've never seen it, I'll explain here:

It means your local `git` isn't configured with an email address tied to your GitHub account. 
You can fix by running these commands from the root of your copy of `pkgnet` (substituting in your email)

```git
git config --global user.email "whatever-email-is-tied-to-your-github@whatever.com"
git reset --soft HEAD~1
git commit -m "removed redundant colons from docs"
git push origin master --force
```

You'll know this worked if you go to https://github.com/uptake/pkgnet/pull/284/commits and see your username on the commit :grinning:

**Review by jayqi — APPROVED** [review]
Changes look good to me as well.

**Comment by KKulma** [comment]
> git push origin master --force

hi there! Thanks so much for such a thorough commentary and a small tutorial and how to set up my git config 👍 Never paid attention to how my commits appear! Anywho, it's all fixed now and thanks again for accepting my contribution!

**Review by jameslamb — APPROVED** [review]
looks great, thanks again for taking the time to contribute here. We hope you'll come back to contribute in the future!

**Pull request merged**
